job_search/employer_app/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', main, name='main_page')
]

job_search/job_search/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls'), name='user'),
    path('', include('employer_app.urls'), name='employer_app'),
    path('vacancy/', include('vacancy.urls'), name='vacancy'),
    path('resume/', include('resume.urls'), name='resume'),
]

job_search/users/urls.py
from django.urls import path
from .views import login, registration
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('logout/', LogoutView.as_view(next_page='main_page'), name='logout')
]

job_search/employer_app/views.py
from django.shortcuts import render


# Create your views here.
def main(request):
    return render(request, 'employer_app/main_page.html', {})

job_search/employer_app/templates/employer_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--    Bootstrap css and js-->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/js/bootstrap.js' %}">


    <!--    my fonts Kalnia( 400 and 700) and Nunito(400) -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Kalnia:wght@400;700&family=Nunito&display=swap" rel="stylesheet">

    <!--    for navbar -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    {% block css %} {% endblock css %}
</head>
<body>
{% block content %}

{% block static %}
{% endblock static %}

{% endblock content %}
</body>
</html>

job_search/employer_app/templates/employer_app/main_page.html
{% extends 'employer_app/base.html' %}
{% load static %}
{% block css %}
<style>
    body {
        font-family: 'Kalnia', serif;
        }
.top{
 color:#000000;
 text-align:center;
 padding-top:0px;
 padding-bottom:50px;
 position: absolute;
  top: 30%; /* Регулируйте положение класса top по вертикали по вашим потребностям */
  left: 50%; /* Регулируйте положение класса top по горизонтали по вашим потребностям */
  transform: translate(-50%, -50%); /* Центрируем класс top относительно карусели */
  z-index: 2;

}
</style>
{% endblock css %}
{% block content %}
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        {% if request.user.is_authenticated %}
        <a class="navbar-brand" href="#">Добро пожаловать {{ request.user }}!</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link active" aria-current="page" href="{% url 'all_vacancy' %}">Вакансии<span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Резюме</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Выход</a>
                </li>
            </ul>
        </div>
        {% else %}
        <a class="navbar-brand" href="#">Work.by</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent2"
                aria-controls="navbarSupportedContent2" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent2">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'users:login' %}">Вход</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:registration' %}">Регистрация</a>
                </li>
            </ul>
        </div>
        {% endif %}
    </nav>
    <div>
        <section class="top">
                <h3 class="title">Сайт для поиска работы</h3>
                <h3 class="title">Найдите работу вместе с нами!</h3>
        </section>
    </div>
</div>
{% endblock content %}